[package]
name = "march_1_21"
version = "0.1.0"
authors = ["matt <m@gilk.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15"