[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Matt Gilk <m@gilk.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.16"